#!/bin/bash
#usage: log_gen <num_iters> <call to wrap> <program + args>
TIMESTAMP=$(date +%Y-%m-%d-%T)
FILENAME=$2_$3_$TIMESTAMP.txt
LINE="--------------------------------------------------------------------------------------------"
for i in $(seq 1 $1)
do	
	echo $LINE >> logs/$FILENAME
	./set_seed &
	SEED_ID=$!
	sleep 1
	LD_PRELOAD=$PWD/wrappers/$2_wrapper.so ${@:3} >> logs/$FILENAME 2>&1
	echo $LINE >> logs/$FILENAME
	kill $SEED_ID
done

